-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgQjRZLibgixsGXHyE
NOMypgp9xOqzRK0WIOgkoPTc/uygCgYIKoZIzj0DAQehRANCAASRb1Fpp9ZdrjYY
7b6dna9KqcpvduXq6ibmv4hLP39V+sd8mXeiTh1t+gWBp6KSLxwAQG7KEVJzlyh1
+nDkqs3i
-----END PRIVATE KEY-----